language: python

sudo: false

env:
  matrix:
    - LUA="lua 5.1" SOCKET=true
    - LUA="lua 5.1"
    - LUA="lua 5.2" SOCKET=true
    - LUA="lua 5.2"
    - LUA="lua 5.3" SOCKET=true
    - LUA="lua 5.3"
    - LUA="luajit 2.0"
    - LUA="luajit 2.1" SOCKET=true SYSCALL=true
    - LUA="luajit 2.1" SYSCALL=true
    - LUA="luajit 2.1"
    - LUA="luajit @"

before_install:
  - pip install hererocks
  - hererocks here -r^ --$LUA # Install latest LuaRocks version
                              # plus the Lua version for this build job
                              # into 'here' subdirectory
  - export PATH=$PATH:$PWD/here/bin # Add directory with all installed binaries to PATH
  - eval `luarocks path --bin`
  - luarocks install luacov-coveralls
  - luarocks install busted

install:
  - luarocks make
  - if [ "$SOCKET" = "true" ]; then luarocks install luasocket; fi
  - if [ "$SYSCALL" = "true" ]; then luarocks install ljsyscall; fi

script:
  - busted -c

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
