language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit2.0
    - LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install luacov-coveralls
  - luarocks install busted

install:
  - luarocks make

script:
  - busted -c

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
